GEMINI_API_KEY = "AIzaSyAz0EeIPxgsuM_3UCez1Stl4ZkN_TtNBvM"
MONGO_URI = "mongodb+srv://fatinamira_db_user:AtJjcGO8bbByaWRg@car.zrckdlq.mongodb.net/?retryWrites=true&w=majority&tls=true&tlsAllowInvalidCertificates=true&serverSelectionTimeoutMS=5000"
